import esbuild from "esbuild";
import process from "process";
import copy from 'esbuild-plugin-copy-watch';
import builtins from 'builtin-modules';

import { readFile } from 'fs/promises';
const manifest = JSON.parse(
  await readFile(
    new URL('./manifest.json', import.meta.url)
  )
);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: `../test-plugin-vault/.obsidian/plugins/${manifest.id}/`,
	plugins: [
		copy([
			{
				from: './styles.css',
				to: '',
			},
			{
				from: './manifest.json',
				to: '',
			},
		]),
	],
}).catch(() => process.exit(1));
